// Generated by tools/generate_flattened_submission.py
// Source config: rust/bot/configs/submission_current.json
// This file is intended for single-file CodinGame submission builds.

mod engine {
    pub mod coord {
        use std::cmp::Ordering;

        #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
        pub struct Coord {
            pub x: i32,
            pub y: i32,
        }

        impl Coord {
            pub const fn new(x: i32, y: i32) -> Self {
                Self { x, y }
            }

            pub const fn add(self, dx: i32, dy: i32) -> Self {
                Self::new(self.x + dx, self.y + dy)
            }

            pub const fn add_coord(self, other: Coord) -> Self {
                Self::new(self.x + other.x, self.y + other.y)
            }

            pub fn manhattan_to(self, other: Coord) -> i32 {
                (self.x - other.x).abs() + (self.y - other.y).abs()
            }

            pub fn to_int_string(self) -> String {
                format!("{} {}", self.x, self.y)
            }
        }

        impl Ord for Coord {
            fn cmp(&self, other: &Self) -> Ordering {
                match self.x.cmp(&other.x) {
                    Ordering::Equal => self.y.cmp(&other.y),
                    ord => ord,
                }
            }
        }

        impl PartialOrd for Coord {
            fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
                Some(self.cmp(other))
            }
        }
    }
    pub mod direction {
        use super::Coord;

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum Direction {
            North,
            East,
            South,
            West,
            Unset,
        }

        impl Direction {
            pub const ALL: [Direction; 4] = [
                Direction::North,
                Direction::East,
                Direction::South,
                Direction::West,
            ];

            pub const fn delta(self) -> Coord {
                match self {
                    Direction::North => Coord::new(0, -1),
                    Direction::East => Coord::new(1, 0),
                    Direction::South => Coord::new(0, 1),
                    Direction::West => Coord::new(-1, 0),
                    Direction::Unset => Coord::new(0, 0),
                }
            }

            pub const fn alias(self) -> &'static str {
                match self {
                    Direction::North => "N",
                    Direction::East => "E",
                    Direction::South => "S",
                    Direction::West => "W",
                    Direction::Unset => "X",
                }
            }

            pub const fn opposite(self) -> Direction {
                match self {
                    Direction::North => Direction::South,
                    Direction::East => Direction::West,
                    Direction::South => Direction::North,
                    Direction::West => Direction::East,
                    Direction::Unset => Direction::Unset,
                }
            }

            pub const fn from_coord(coord: Coord) -> Direction {
                match (coord.x, coord.y) {
                    (0, -1) => Direction::North,
                    (1, 0) => Direction::East,
                    (0, 1) => Direction::South,
                    (-1, 0) => Direction::West,
                    _ => Direction::Unset,
                }
            }

            pub fn from_command(command: &str) -> Option<Direction> {
                match command {
                    "UP" => Some(Direction::North),
                    "RIGHT" => Some(Direction::East),
                    "DOWN" => Some(Direction::South),
                    "LEFT" => Some(Direction::West),
                    _ => None,
                }
            }
        }
    }
    pub mod map {
        use std::collections::{BTreeSet, VecDeque};

        use super::{Coord, Direction};

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum TileType {
            Empty,
            Wall,
        }

        #[derive(Clone, Debug, Eq, PartialEq)]
        pub struct Grid {
            pub width: i32,
            pub height: i32,
            pub tiles: Vec<TileType>,
            pub spawns: Vec<Coord>,
            pub apples: Vec<Coord>,
        }

        impl Grid {
            pub const ADJACENCY: [Coord; 4] = [
                Direction::North.delta(),
                Direction::East.delta(),
                Direction::South.delta(),
                Direction::West.delta(),
            ];

            pub const ADJACENCY_8: [Coord; 8] = [
                Direction::North.delta(),
                Direction::East.delta(),
                Direction::South.delta(),
                Direction::West.delta(),
                Coord::new(-1, -1),
                Coord::new(1, 1),
                Coord::new(1, -1),
                Coord::new(-1, 1),
            ];

            pub fn new(width: i32, height: i32) -> Self {
                let len = (width * height) as usize;
                Self {
                    width,
                    height,
                    tiles: vec![TileType::Empty; len],
                    spawns: Vec::new(),
                    apples: Vec::new(),
                }
            }

            pub fn is_valid(&self, coord: Coord) -> bool {
                coord.x >= 0 && coord.x < self.width && coord.y >= 0 && coord.y < self.height
            }

            pub fn index(&self, coord: Coord) -> Option<usize> {
                self.is_valid(coord)
                    .then_some((coord.y * self.width + coord.x) as usize)
            }

            pub fn get(&self, coord: Coord) -> Option<TileType> {
                self.index(coord).map(|idx| self.tiles[idx])
            }

            pub fn set(&mut self, coord: Coord, tile: TileType) {
                if let Some(idx) = self.index(coord) {
                    self.tiles[idx] = tile;
                }
            }

            pub fn coords(&self) -> Vec<Coord> {
                let mut coords = Vec::with_capacity(self.tiles.len());
                for y in 0..self.height {
                    for x in 0..self.width {
                        coords.push(Coord::new(x, y));
                    }
                }
                coords
            }

            pub fn neighbours(&self, coord: Coord, adjacency: &[Coord]) -> Vec<Coord> {
                adjacency
                    .iter()
                    .map(|delta| coord.add_coord(*delta))
                    .filter(|next| self.is_valid(*next))
                    .collect()
            }

            pub fn opposite(&self, coord: Coord) -> Coord {
                Coord::new(self.width - coord.x - 1, coord.y)
            }

            pub fn sorted_unique_apples(&mut self) {
                let mut set = BTreeSet::new();
                for apple in self.apples.drain(..) {
                    set.insert(apple);
                }
                self.apples = set.into_iter().collect();
            }

            pub fn detect_air_pockets(&self) -> Vec<BTreeSet<Coord>> {
                self.detect_regions(
                    self.coords()
                        .into_iter()
                        .filter(|coord| self.get(*coord) == Some(TileType::Empty))
                        .collect(),
                )
            }

            pub fn detect_spawn_islands(&self) -> Vec<BTreeSet<Coord>> {
                let mut result = Vec::new();
                let candidates = self.spawns.iter().copied().collect::<BTreeSet<_>>();
                let mut seen = BTreeSet::new();
                for start in self.spawns.iter().copied() {
                    if seen.contains(&start) {
                        continue;
                    }
                    let mut current = BTreeSet::new();
                    let mut queue = VecDeque::from([start]);
                    seen.insert(start);
                    while let Some(coord) = queue.pop_front() {
                        current.insert(coord);
                        for next in self.neighbours(coord, &Self::ADJACENCY) {
                            if !candidates.contains(&next) || seen.contains(&next) {
                                continue;
                            }
                            seen.insert(next);
                            queue.push_back(next);
                        }
                    }
                    result.push(current);
                }
                result
            }

            fn detect_regions(&self, candidates: BTreeSet<Coord>) -> Vec<BTreeSet<Coord>> {
                let mut result = Vec::new();
                let mut seen = BTreeSet::new();
                for start in candidates.iter().copied() {
                    if seen.contains(&start) {
                        continue;
                    }
                    let mut current = BTreeSet::new();
                    let mut queue = VecDeque::from([start]);
                    seen.insert(start);
                    while let Some(coord) = queue.pop_front() {
                        current.insert(coord);
                        for next in self.neighbours(coord, &Self::ADJACENCY) {
                            if !candidates.contains(&next) || seen.contains(&next) {
                                continue;
                            }
                            seen.insert(next);
                            queue.push_back(next);
                        }
                    }
                    result.push(current);
                }
                result
            }

            pub fn detect_lowest_island(&self) -> Vec<Coord> {
                let start = Coord::new(0, self.height - 1);
                if self.get(start) != Some(TileType::Wall) {
                    return Vec::new();
                }

                let mut result = Vec::new();
                let mut seen = BTreeSet::new();
                let mut queue = VecDeque::from([start]);
                seen.insert(start);
                while let Some(coord) = queue.pop_front() {
                    result.push(coord);
                    for next in self.neighbours(coord, &Self::ADJACENCY) {
                        if seen.contains(&next) || self.get(next) != Some(TileType::Wall) {
                            continue;
                        }
                        seen.insert(next);
                        queue.push_back(next);
                    }
                }
                result
            }

            pub fn get_free_above(&self, coord: Coord, count: i32) -> Vec<Coord> {
                let mut result = Vec::new();
                for step in 1..=count {
                    let above = Coord::new(coord.x, coord.y - step);
                    if self.get(above) == Some(TileType::Empty) {
                        result.push(above);
                    } else {
                        break;
                    }
                }
                result
            }
        }
    }
    pub mod state {
        use std::collections::{BTreeMap, BTreeSet, VecDeque};

        use super::{Coord, Direction, Grid, TileType};

        #[derive(Clone, Debug, Eq, PartialEq)]
        pub struct BirdState {
            pub id: i32,
            pub owner: usize,
            pub body: VecDeque<Coord>,
            pub alive: bool,
            pub direction: Option<Direction>,
        }

        impl BirdState {
            pub fn head(&self) -> Coord {
                *self.body.front().expect("bird has at least one segment")
            }

            pub fn facing(&self) -> Direction {
                if self.body.len() < 2 {
                    Direction::Unset
                } else {
                    let head = self.body[0];
                    let neck = self.body[1];
                    Direction::from_coord(Coord::new(head.x - neck.x, head.y - neck.y))
                }
            }

            pub fn length(&self) -> usize {
                self.body.len()
            }
        }

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum BirdCommand {
            Keep,
            Turn(Direction),
        }

        #[derive(Clone, Debug, Default, Eq, PartialEq)]
        pub struct PlayerAction {
            pub per_bird: BTreeMap<i32, BirdCommand>,
        }

        impl PlayerAction {
            pub fn command_for(&self, bird_id: i32) -> BirdCommand {
                self.per_bird
                    .get(&bird_id)
                    .copied()
                    .unwrap_or(BirdCommand::Keep)
            }
        }

        #[derive(Clone, Debug, Eq, PartialEq)]
        pub struct GameState {
            pub grid: Grid,
            pub birds: Vec<BirdState>,
            pub losses: [i32; 2],
            pub turn: i32,
        }

        #[derive(Clone, Debug, Eq, PartialEq)]
        pub struct StepResult {
            pub game_over: bool,
            pub body_scores: [i32; 2],
            pub final_scores: [i32; 2],
        }

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum TerminalReason {
            ApplesExhausted,
            PlayerEliminated(usize),
            TurnLimitReached,
        }

        #[derive(Clone, Debug, Eq, PartialEq)]
        pub struct FinalResult {
            pub terminal: bool,
            pub reason: Option<TerminalReason>,
            pub body_scores: [i32; 2],
            pub final_scores: [i32; 2],
            pub losses: [i32; 2],
            pub body_diff: i32,
            pub loss_diff: i32,
            pub winner: Option<usize>,
        }

        impl FinalResult {
            pub fn body_diff_for(&self, owner: usize) -> i32 {
                if owner == 0 {
                    self.body_diff
                } else {
                    -self.body_diff
                }
            }

            pub fn loss_diff_for(&self, owner: usize) -> i32 {
                if owner == 0 {
                    self.loss_diff
                } else {
                    -self.loss_diff
                }
            }
        }

        #[derive(Clone, Debug, Eq, PartialEq)]
        pub struct VisibilityState {
            pub player_index: usize,
            pub my_ids: Vec<i32>,
            pub opp_ids: Vec<i32>,
            pub state: GameState,
        }

        impl GameState {
            pub fn new(grid: Grid) -> Self {
                Self {
                    grid,
                    birds: Vec::new(),
                    losses: [0, 0],
                    turn: 0,
                }
            }

            pub fn add_bird(
                &mut self,
                id: i32,
                owner: usize,
                body: Vec<Coord>,
                direction: Option<Direction>,
            ) {
                self.birds.push(BirdState {
                    id,
                    owner,
                    body: body.into_iter().collect(),
                    alive: true,
                    direction,
                });
                self.birds.sort_by_key(|bird| bird.id);
            }

            pub fn body_scores(&self) -> [i32; 2] {
                let mut scores = [0, 0];
                for bird in self.live_birds() {
                    scores[bird.owner] += bird.body.len() as i32;
                }
                scores
            }

            pub fn final_scores(&self) -> [i32; 2] {
                let mut scores = self.body_scores();
                if scores[0] == scores[1] {
                    scores[0] -= self.losses[0];
                    scores[1] -= self.losses[1];
                }
                scores
            }

            pub fn live_birds(&self) -> impl Iterator<Item = &BirdState> {
                self.birds.iter().filter(|bird| bird.alive)
            }

            pub fn live_birds_mut(&mut self) -> impl Iterator<Item = &mut BirdState> {
                self.birds.iter_mut().filter(|bird| bird.alive)
            }

            pub fn birds_for_player(&self, owner: usize) -> impl Iterator<Item = &BirdState> {
                self.birds.iter().filter(move |bird| bird.owner == owner)
            }

            pub fn legal_commands_for_bird(&self, bird_id: i32) -> Vec<BirdCommand> {
                let Some(bird) = self
                    .birds
                    .iter()
                    .find(|bird| bird.id == bird_id && bird.alive)
                else {
                    return Vec::new();
                };
                let facing = bird.facing();
                let mut commands = vec![BirdCommand::Keep];
                for direction in Direction::ALL {
                    if facing != Direction::Unset && direction == facing.opposite() {
                        continue;
                    }
                    if direction == facing {
                        continue;
                    }
                    commands.push(BirdCommand::Turn(direction));
                }
                commands
            }

            pub fn legal_joint_actions(&self, owner: usize) -> Vec<PlayerAction> {
                let birds: Vec<_> = self
                    .birds_for_player(owner)
                    .filter(|bird| bird.alive)
                    .map(|bird| bird.id)
                    .collect();
                let mut result = Vec::new();
                let mut current = PlayerAction::default();
                self.enumerate_actions(&birds, 0, &mut current, &mut result);
                if result.is_empty() {
                    result.push(PlayerAction::default());
                }
                result
            }

            fn enumerate_actions(
                &self,
                birds: &[i32],
                idx: usize,
                current: &mut PlayerAction,
                output: &mut Vec<PlayerAction>,
            ) {
                if idx == birds.len() {
                    output.push(current.clone());
                    return;
                }

                let bird_id = birds[idx];
                for command in self.legal_commands_for_bird(bird_id) {
                    match command {
                        BirdCommand::Keep => {
                            current.per_bird.remove(&bird_id);
                        }
                        BirdCommand::Turn(direction) => {
                            current
                                .per_bird
                                .insert(bird_id, BirdCommand::Turn(direction));
                        }
                    }
                    self.enumerate_actions(birds, idx + 1, current, output);
                }
                current.per_bird.remove(&bird_id);
            }

            pub fn encode_player_view(&self, player_index: usize) -> VisibilityState {
                let mut my_ids = self
                    .birds_for_player(player_index)
                    .map(|bird| bird.id)
                    .collect::<Vec<_>>();
                my_ids.sort();
                let mut opp_ids = self
                    .birds_for_player(1 - player_index)
                    .map(|bird| bird.id)
                    .collect::<Vec<_>>();
                opp_ids.sort();
                VisibilityState {
                    player_index,
                    my_ids,
                    opp_ids,
                    state: self.clone(),
                }
            }

            pub fn step(&mut self, p0: &PlayerAction, p1: &PlayerAction) -> StepResult {
                self.turn += 1;
                self.reset_turn_state();
                self.apply_moves(p0, p1);
                self.apply_eats();
                self.apply_beheadings();
                self.apply_falls();

                let body_scores = self.body_scores();
                let final_scores = self.final_scores();
                StepResult {
                    game_over: self.is_game_over(),
                    body_scores,
                    final_scores,
                }
            }

            fn reset_turn_state(&mut self) {
                for bird in self.live_birds_mut() {
                    bird.direction = None;
                }
            }

            fn apply_moves(&mut self, p0: &PlayerAction, p1: &PlayerAction) {
                for idx in 0..self.birds.len() {
                    if !self.birds[idx].alive {
                        continue;
                    }
                    let command = if self.birds[idx].owner == 0 {
                        p0.command_for(self.birds[idx].id)
                    } else {
                        p1.command_for(self.birds[idx].id)
                    };

                    match command {
                        BirdCommand::Keep => {
                            if self.birds[idx].direction.is_none()
                                || self.birds[idx].direction == Some(Direction::Unset)
                            {
                                self.birds[idx].direction = Some(self.birds[idx].facing());
                            }
                        }
                        BirdCommand::Turn(direction) => {
                            let facing = self.birds[idx].facing();
                            if facing != Direction::Unset && direction == facing.opposite() {
                                self.birds[idx].direction = Some(facing);
                            } else {
                                self.birds[idx].direction = Some(direction);
                            }
                        }
                    }

                    let direction = self.birds[idx].direction.unwrap_or(Direction::Unset);
                    let new_head = self.birds[idx].head().add_coord(direction.delta());
                    let will_eat = self.grid.apples.contains(&new_head);
                    if !will_eat {
                        self.birds[idx].body.pop_back();
                    }
                    self.birds[idx].body.push_front(new_head);
                }
            }

            fn apply_eats(&mut self) {
                let mut apples_eaten = BTreeSet::new();
                for bird in self.live_birds() {
                    if self.grid.apples.contains(&bird.head()) {
                        apples_eaten.insert(bird.head());
                    }
                }
                self.grid
                    .apples
                    .retain(|apple| !apples_eaten.contains(apple));
            }

            fn apply_beheadings(&mut self) {
                let alive_indices: Vec<_> = self
                    .birds
                    .iter()
                    .enumerate()
                    .filter_map(|(idx, bird)| bird.alive.then_some(idx))
                    .collect();
                let mut to_behead = Vec::new();

                for idx in alive_indices {
                    let head = self.birds[idx].head();
                    let is_in_wall = self.grid.get(head) == Some(TileType::Wall);
                    let intersecting: Vec<_> = self
                        .birds
                        .iter()
                        .filter(|bird| bird.alive && bird.body.contains(&head))
                        .collect();
                    let is_in_bird = intersecting.iter().any(|other| {
                        other.id != self.birds[idx].id
                            || other
                                .body
                                .iter()
                                .skip(1)
                                .any(|segment| *segment == other.head())
                    });

                    if is_in_wall || is_in_bird {
                        to_behead.push(idx);
                    }
                }

                for idx in to_behead {
                    let owner = self.birds[idx].owner;
                    if self.birds[idx].body.len() <= 3 {
                        self.losses[owner] += self.birds[idx].body.len() as i32;
                        self.birds[idx].alive = false;
                    } else {
                        self.birds[idx].body.pop_front();
                        self.losses[owner] += 1;
                    }
                }
            }

            fn apply_falls(&mut self) {
                let mut something_fell = true;
                while something_fell {
                    something_fell = false;
                    while self.apply_individual_falls() {
                        something_fell = true;
                    }
                    if self.apply_intercoiled_falls() {
                        something_fell = true;
                    }
                }
            }

            fn apply_individual_falls(&mut self) -> bool {
                let mut moved = false;
                let alive_indices: Vec<_> = self
                    .birds
                    .iter()
                    .enumerate()
                    .filter_map(|(idx, bird)| bird.alive.then_some(idx))
                    .collect();
                for idx in alive_indices {
                    let body: Vec<_> = self.birds[idx].body.iter().copied().collect();
                    let can_fall = body
                        .iter()
                        .all(|coord| !self.something_solid_under(*coord, &body));
                    if can_fall {
                        moved = true;
                        self.shift_bird_down(idx);
                        if self.birds[idx]
                            .body
                            .iter()
                            .all(|coord| coord.y >= self.grid.height + 1)
                        {
                            self.birds[idx].alive = false;
                        }
                    }
                }
                moved
            }

            fn apply_intercoiled_falls(&mut self) -> bool {
                let groups = self.intercoiled_groups();
                let mut moved = false;
                for group in groups {
                    let meta_body: Vec<_> = group
                        .iter()
                        .flat_map(|idx| self.birds[*idx].body.iter().copied())
                        .collect();
                    let can_fall = meta_body
                        .iter()
                        .all(|coord| !self.something_solid_under(*coord, &meta_body));
                    if !can_fall {
                        continue;
                    }
                    moved = true;
                    for idx in group {
                        self.shift_bird_down(idx);
                        if self.birds[idx].head().y >= self.grid.height {
                            self.birds[idx].alive = false;
                        }
                    }
                }
                moved
            }

            fn intercoiled_groups(&self) -> Vec<Vec<usize>> {
                let alive_indices: Vec<_> = self
                    .birds
                    .iter()
                    .enumerate()
                    .filter_map(|(idx, bird)| bird.alive.then_some(idx))
                    .collect();
                let mut groups = Vec::new();
                let mut seen = BTreeSet::new();
                for idx in alive_indices.iter().copied() {
                    if seen.contains(&idx) {
                        continue;
                    }
                    let mut group = Vec::new();
                    let mut queue = VecDeque::from([idx]);
                    while let Some(current) = queue.pop_front() {
                        if !seen.insert(current) {
                            continue;
                        }
                        group.push(current);
                        for other in alive_indices.iter().copied() {
                            if current == other || seen.contains(&other) {
                                continue;
                            }
                            if birds_are_touching(&self.birds[current], &self.birds[other]) {
                                queue.push_back(other);
                            }
                        }
                    }
                    if group.len() > 1 {
                        groups.push(group);
                    }
                }
                groups
            }

            fn shift_bird_down(&mut self, idx: usize) {
                for coord in self.birds[idx].body.iter_mut() {
                    coord.y += 1;
                }
            }

            fn something_solid_under(&self, coord: Coord, ignore_body: &[Coord]) -> bool {
                let below = coord.add(0, 1);
                if ignore_body.contains(&below) {
                    return false;
                }
                if self.grid.get(below) == Some(TileType::Wall) {
                    return true;
                }
                if self
                    .birds
                    .iter()
                    .any(|bird| bird.alive && bird.body.contains(&below))
                {
                    return true;
                }
                self.grid.apples.contains(&below)
            }

            pub fn is_game_over(&self) -> bool {
                self.grid.apples.is_empty()
                    || (0..=1).any(|owner| self.birds_for_player(owner).all(|bird| !bird.alive))
            }

            pub fn terminal_reason(&self, max_turns: i32) -> Option<TerminalReason> {
                if self.grid.apples.is_empty() {
                    return Some(TerminalReason::ApplesExhausted);
                }
                if let Some(owner) =
                    (0..=1).find(|owner| self.birds_for_player(*owner).all(|bird| !bird.alive))
                {
                    return Some(TerminalReason::PlayerEliminated(owner));
                }
                if self.turn >= max_turns {
                    return Some(TerminalReason::TurnLimitReached);
                }
                None
            }

            pub fn is_terminal(&self, max_turns: i32) -> bool {
                self.terminal_reason(max_turns).is_some()
            }

            pub fn final_result(&self, max_turns: i32) -> FinalResult {
                let body_scores = self.body_scores();
                let final_scores = self.final_scores();
                let body_diff = body_scores[0] - body_scores[1];
                let loss_diff = self.losses[1] - self.losses[0];
                let winner = if body_diff > 0 {
                    Some(0)
                } else if body_diff < 0 {
                    Some(1)
                } else if loss_diff > 0 {
                    Some(0)
                } else if loss_diff < 0 {
                    Some(1)
                } else {
                    None
                };

                FinalResult {
                    terminal: self.is_terminal(max_turns),
                    reason: self.terminal_reason(max_turns),
                    body_scores,
                    final_scores,
                    losses: self.losses,
                    body_diff,
                    loss_diff,
                    winner,
                }
            }
        }

        fn birds_are_touching(a: &BirdState, b: &BirdState) -> bool {
            a.body
                .iter()
                .any(|left| b.body.iter().any(|right| left.manhattan_to(*right) == 1))
        }
    }
    pub use self::coord::Coord;
    pub use self::direction::Direction;
    pub use self::map::{Grid, TileType};
    pub use self::state::{
        BirdCommand, BirdState, FinalResult, GameState, PlayerAction, StepResult, TerminalReason,
        VisibilityState,
    };
}

mod bot {
    pub mod config {
        #[derive(Clone, Copy, Debug, PartialEq)]
        pub struct EvalWeights {
            pub body: f64,
            pub loss: f64,
            pub mobility: f64,
            pub apple: f64,
            pub stability: f64,
            pub breakpoint: f64,
            pub fragile_attack: f64,
            pub terminal: f64,
        }

        impl Default for EvalWeights {
            fn default() -> Self {
                Self {
                    body: 120.0,
                    loss: 18.0,
                    mobility: 7.5,
                    apple: 16.0,
                    stability: 10.0,
                    breakpoint: 9.0,
                    fragile_attack: 8.0,
                    terminal: 10000.0,
                }
            }
        }

        #[derive(Clone, Copy, Debug, PartialEq)]
        pub struct SearchConfig {
            pub first_turn_ms: u64,
            pub later_turn_ms: u64,
            pub deepen_top_my: usize,
            pub deepen_top_opp: usize,
            pub deepen_child_my: usize,
            pub deepen_child_opp: usize,
            pub extra_nodes_after_root: u64,
        }

        impl Default for SearchConfig {
            fn default() -> Self {
                Self {
                    first_turn_ms: 850,
                    later_turn_ms: 40,
                    deepen_top_my: 6,
                    deepen_top_opp: 8,
                    deepen_child_my: 3,
                    deepen_child_opp: 3,
                    extra_nodes_after_root: 5000,
                }
            }
        }

        #[derive(Clone, Debug, PartialEq)]
        pub struct BotConfig {
            pub name: String,
            pub eval: EvalWeights,
            pub search: SearchConfig,
        }

        impl Default for BotConfig {
            fn default() -> Self {
                Self::embedded()
            }
        }

        impl BotConfig {
            pub fn embedded() -> Self {
                Self {
                    name: "submission_current".to_owned(),
                    eval: EvalWeights::default(),
                    search: SearchConfig::default(),
                }
            }
        }
    }
    pub mod eval {
        use crate::engine::{Coord, GameState, TileType};

        use super::config::EvalWeights;

        pub fn evaluate(
            state: &GameState,
            owner: usize,
            max_turns: i32,
            weights: &EvalWeights,
        ) -> f64 {
            if state.is_terminal(max_turns) {
                let final_result = state.final_result(max_turns);
                return weights.terminal * f64::from(final_result.body_diff_for(owner))
                    + f64::from(final_result.loss_diff_for(owner));
            }

            let body_scores = state.body_scores();
            let body_diff = f64::from(body_scores[owner] - body_scores[1 - owner]);
            let loss_diff = f64::from(state.losses[1 - owner] - state.losses[owner]);
            let mobility = mobility_score(state, owner);
            let apple_race = apple_race_score(state, owner);
            let stability = support_stability_score(state, owner);
            let breakpoint = breakpoint_score(state, owner);
            let pressure = fragile_attack_score(state, owner);

            weights.body * body_diff
                + weights.loss * loss_diff
                + weights.mobility * mobility
                + weights.apple * apple_race
                + weights.stability * stability
                + weights.breakpoint * breakpoint
                + weights.fragile_attack * pressure
        }

        fn mobility_score(state: &GameState, owner: usize) -> f64 {
            let mut total = 0.0;
            for bird in state.birds_for_player(owner).filter(|bird| bird.alive) {
                total += state.legal_commands_for_bird(bird.id).len() as f64;
            }
            for bird in state.birds_for_player(1 - owner).filter(|bird| bird.alive) {
                total -= state.legal_commands_for_bird(bird.id).len() as f64;
            }
            total
        }

        fn apple_race_score(state: &GameState, owner: usize) -> f64 {
            let my_heads = state
                .birds_for_player(owner)
                .filter(|bird| bird.alive)
                .map(|bird| bird.head())
                .collect::<Vec<_>>();
            let opp_heads = state
                .birds_for_player(1 - owner)
                .filter(|bird| bird.alive)
                .map(|bird| bird.head())
                .collect::<Vec<_>>();
            state
                .grid
                .apples
                .iter()
                .map(|apple| {
                    let my_dist = min_distance(*apple, &my_heads);
                    let opp_dist = min_distance(*apple, &opp_heads);
                    f64::from(opp_dist - my_dist) / f64::from((my_dist + opp_dist + 1).max(1))
                })
                .sum()
        }

        fn support_stability_score(state: &GameState, owner: usize) -> f64 {
            let mut score = 0.0;
            for bird in state.birds.iter().filter(|bird| bird.alive) {
                let supported = bird
                    .body
                    .iter()
                    .any(|coord| has_solid_below(state, bird.id, *coord));
                let value = if supported { 1.0 } else { -1.0 };
                if bird.owner == owner {
                    score += value;
                } else {
                    score -= value;
                }
            }
            score
        }

        fn breakpoint_score(state: &GameState, owner: usize) -> f64 {
            let own = state
                .birds_for_player(owner)
                .filter(|bird| bird.alive)
                .map(|bird| usize::from(bird.length() >= 4) as f64)
                .sum::<f64>();
            let opp = state
                .birds_for_player(1 - owner)
                .filter(|bird| bird.alive)
                .map(|bird| usize::from(bird.length() >= 4) as f64)
                .sum::<f64>();
            own - opp
        }

        fn fragile_attack_score(state: &GameState, owner: usize) -> f64 {
            let my_heads = state
                .birds_for_player(owner)
                .filter(|bird| bird.alive)
                .map(|bird| bird.head())
                .collect::<Vec<_>>();
            state
                .birds_for_player(1 - owner)
                .filter(|bird| bird.alive && bird.length() <= 3)
                .map(|bird| {
                    let closest = min_distance(bird.head(), &my_heads);
                    1.0 / f64::from(closest + 1)
                })
                .sum()
        }

        fn has_solid_below(state: &GameState, bird_id: i32, coord: Coord) -> bool {
            let below = coord.add(0, 1);
            if state.grid.get(below) == Some(TileType::Wall) {
                return true;
            }
            if state.grid.apples.contains(&below) {
                return true;
            }
            state
                .birds
                .iter()
                .filter(|bird| bird.alive && bird.id != bird_id)
                .any(|bird| bird.body.contains(&below))
        }

        fn min_distance(target: Coord, coords: &[Coord]) -> i32 {
            coords
                .iter()
                .map(|coord| coord.manhattan_to(target))
                .min()
                .unwrap_or(99)
        }
    }
    pub mod input {
        use std::collections::{BTreeMap, BTreeSet, VecDeque};
        use std::io::{self, BufRead};

        use crate::engine::{BirdState, Coord, GameState, Grid, TileType};

        #[derive(Clone, Debug)]
        pub struct FrameObservation {
            pub apples: Vec<Coord>,
            pub live_birds: BTreeMap<i32, Vec<Coord>>,
        }

        #[derive(Clone, Debug)]
        pub struct BotIo {
            pub player_index: usize,
            pub my_ids: Vec<i32>,
            pub opp_ids: Vec<i32>,
            pub template_grid: Grid,
        }

        impl BotIo {
            pub fn read(reader: &mut impl BufRead) -> io::Result<Self> {
                let player_index = read_line(reader)?.parse::<usize>().map_err(parse_err)?;
                let width = read_line(reader)?.parse::<i32>().map_err(parse_err)?;
                let height = read_line(reader)?.parse::<i32>().map_err(parse_err)?;
                let mut grid = Grid::new(width, height);
                for y in 0..height {
                    let row = read_line(reader)?;
                    for (x, ch) in row.chars().enumerate() {
                        if ch == '#' {
                            grid.set(Coord::new(x as i32, y), TileType::Wall);
                        }
                    }
                }
                let birds_per_player = read_line(reader)?.parse::<usize>().map_err(parse_err)?;
                let mut my_ids = Vec::with_capacity(birds_per_player);
                let mut opp_ids = Vec::with_capacity(birds_per_player);
                for _ in 0..birds_per_player {
                    my_ids.push(read_line(reader)?.parse::<i32>().map_err(parse_err)?);
                }
                for _ in 0..birds_per_player {
                    opp_ids.push(read_line(reader)?.parse::<i32>().map_err(parse_err)?);
                }
                Ok(Self {
                    player_index,
                    my_ids,
                    opp_ids,
                    template_grid: grid,
                })
            }

            pub fn read_frame(
                &self,
                reader: &mut impl BufRead,
            ) -> io::Result<Option<FrameObservation>> {
                let Some(apple_count_line) = read_optional_line(reader)? else {
                    return Ok(None);
                };
                let apple_count = apple_count_line.parse::<usize>().map_err(parse_err)?;
                let mut apples = Vec::with_capacity(apple_count);
                for _ in 0..apple_count {
                    apples.push(parse_space_coord(&read_line(reader)?)?);
                }
                let live_bird_count = read_line(reader)?.parse::<usize>().map_err(parse_err)?;
                let mut live_birds = BTreeMap::new();
                for _ in 0..live_bird_count {
                    let line = read_line(reader)?;
                    let (id, body) = parse_bird_line(&line)?;
                    live_birds.insert(id, body);
                }
                Ok(Some(FrameObservation { apples, live_birds }))
            }

            pub fn build_visible_state(
                &self,
                frame: &FrameObservation,
                losses: [i32; 2],
                turn: i32,
            ) -> GameState {
                let mut grid = self.template_grid.clone();
                grid.apples = frame.apples.clone();
                let mut state = GameState {
                    grid,
                    birds: Vec::new(),
                    losses,
                    turn,
                };
                for bird_id in self
                    .my_ids
                    .iter()
                    .chain(self.opp_ids.iter())
                    .copied()
                    .collect::<Vec<_>>()
                {
                    if let Some(body) = frame.live_birds.get(&bird_id) {
                        state.birds.push(BirdState {
                            id: bird_id,
                            owner: self.owner_of(bird_id),
                            body: body.iter().copied().collect::<VecDeque<_>>(),
                            alive: true,
                            direction: None,
                        });
                    } else {
                        state.birds.push(BirdState {
                            id: bird_id,
                            owner: self.owner_of(bird_id),
                            body: VecDeque::new(),
                            alive: false,
                            direction: None,
                        });
                    }
                }
                state.birds.sort_by_key(|bird| bird.id);
                state
            }

            pub fn visible_signature(
                &self,
                state: &GameState,
            ) -> (BTreeSet<Coord>, BTreeMap<i32, Vec<Coord>>) {
                let apples = state.grid.apples.iter().copied().collect::<BTreeSet<_>>();
                let birds = state
                    .birds
                    .iter()
                    .filter(|bird| bird.alive)
                    .map(|bird| (bird.id, bird.body.iter().copied().collect::<Vec<_>>()))
                    .collect::<BTreeMap<_, _>>();
                (apples, birds)
            }

            pub fn observation_signature(
                &self,
                frame: &FrameObservation,
            ) -> (BTreeSet<Coord>, BTreeMap<i32, Vec<Coord>>) {
                (
                    frame.apples.iter().copied().collect::<BTreeSet<_>>(),
                    frame.live_birds.clone(),
                )
            }

            fn owner_of(&self, bird_id: i32) -> usize {
                if self.my_ids.contains(&bird_id) {
                    self.player_index
                } else {
                    1 - self.player_index
                }
            }
        }

        fn read_optional_line(reader: &mut impl BufRead) -> io::Result<Option<String>> {
            let mut line = String::new();
            let bytes = reader.read_line(&mut line)?;
            if bytes == 0 {
                return Ok(None);
            }
            Ok(Some(line.trim().to_owned()))
        }

        fn read_line(reader: &mut impl BufRead) -> io::Result<String> {
            read_optional_line(reader)?
                .ok_or_else(|| io::Error::new(io::ErrorKind::UnexpectedEof, "unexpected EOF"))
        }

        fn parse_err(err: impl ToString) -> io::Error {
            io::Error::new(io::ErrorKind::InvalidData, err.to_string())
        }

        fn parse_space_coord(input: &str) -> io::Result<Coord> {
            let mut parts = input.split_whitespace();
            let x = parts
                .next()
                .ok_or_else(|| parse_err("missing x"))?
                .parse::<i32>()
                .map_err(parse_err)?;
            let y = parts
                .next()
                .ok_or_else(|| parse_err("missing y"))?
                .parse::<i32>()
                .map_err(parse_err)?;
            Ok(Coord::new(x, y))
        }

        fn parse_bird_line(input: &str) -> io::Result<(i32, Vec<Coord>)> {
            let mut parts = input.split_whitespace();
            let id = parts
                .next()
                .ok_or_else(|| parse_err("missing bird id"))?
                .parse::<i32>()
                .map_err(parse_err)?;
            let body = parts.next().ok_or_else(|| parse_err("missing body"))?;
            let coords = body
                .split(':')
                .map(|segment| {
                    let mut pieces = segment.split(',');
                    let x = pieces
                        .next()
                        .ok_or_else(|| parse_err("missing body x"))?
                        .parse::<i32>()
                        .map_err(parse_err)?;
                    let y = pieces
                        .next()
                        .ok_or_else(|| parse_err("missing body y"))?
                        .parse::<i32>()
                        .map_err(parse_err)?;
                    Ok(Coord::new(x, y))
                })
                .collect::<io::Result<Vec<_>>>()?;
            Ok((id, coords))
        }
    }
    pub mod search {
        use std::time::{Duration, Instant};

        use crate::engine::{BirdCommand, Direction, GameState, PlayerAction};

        use super::config::BotConfig;
        use super::eval::evaluate;

        const CONTEST_MAX_TURNS: i32 = 200;

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum SearchBudget {
            TimeMs(u64),
            ExtraNodesAfterRoot(u64),
        }

        impl SearchBudget {
            pub fn budget_type(self) -> &'static str {
                match self {
                    SearchBudget::TimeMs(_) => "time_ms",
                    SearchBudget::ExtraNodesAfterRoot(_) => "extra_nodes_after_root",
                }
            }

            pub fn budget_value(self) -> u64 {
                match self {
                    SearchBudget::TimeMs(value) | SearchBudget::ExtraNodesAfterRoot(value) => value,
                }
            }
        }

        #[derive(Clone, Debug, Default, Eq, PartialEq)]
        pub struct SearchStats {
            pub elapsed_ms: u64,
            pub root_pairs: u64,
            pub extra_nodes: u64,
            pub cutoffs: u64,
            pub tt_hits: u64,
            pub my_action_count: usize,
            pub opp_action_count: usize,
            pub deepened_actions: usize,
        }

        #[derive(Clone, Debug)]
        pub struct SearchOutcome {
            pub action: PlayerAction,
            pub action_id: usize,
            pub action_count: usize,
            pub root_values: Vec<f32>,
            pub score: f64,
            pub mean_score: f64,
            pub stats: SearchStats,
        }

        #[derive(Clone)]
        struct RootResponse {
            opp_index: usize,
            score: f64,
        }

        #[derive(Clone)]
        struct RootAnalysis {
            action: PlayerAction,
            action_id: usize,
            worst_score: f64,
            mean_score: f64,
            responses: Vec<RootResponse>,
        }

        pub fn live_budget_for_turn(config: &BotConfig, turn: i32) -> SearchBudget {
            if turn == 0 {
                SearchBudget::TimeMs(config.search.first_turn_ms)
            } else {
                SearchBudget::TimeMs(config.search.later_turn_ms)
            }
        }

        pub fn choose_action(
            state: &GameState,
            owner: usize,
            config: &BotConfig,
            budget: SearchBudget,
        ) -> SearchOutcome {
            let started = Instant::now();
            let deadline = deadline_for_budget(started, budget);
            let allow_cutoff = matches!(budget, SearchBudget::TimeMs(_));
            let mut extra_nodes_remaining = match budget {
                SearchBudget::TimeMs(_) => u64::MAX,
                SearchBudget::ExtraNodesAfterRoot(nodes) => nodes,
            };

            let my_actions = ordered_joint_actions(state, owner);
            let opp_actions = ordered_joint_actions(state, 1 - owner);
            let my_action_count = my_actions.len();
            let opp_action_count = opp_actions.len();
            let default_action = PlayerAction::default();

            let mut my_order = (0..my_actions.len())
                .map(|idx| {
                    (
                        idx,
                        action_prior(state, owner, &my_actions[idx], &default_action, config),
                    )
                })
                .collect::<Vec<_>>();
            my_order.sort_by(|left, right| right.1.total_cmp(&left.1));

            let mut opp_order = (0..opp_actions.len())
                .map(|idx| {
                    (
                        idx,
                        action_prior(state, owner, &default_action, &opp_actions[idx], config),
                    )
                })
                .collect::<Vec<_>>();
            opp_order.sort_by(|left, right| left.1.total_cmp(&right.1));

            let mut stats = SearchStats {
                my_action_count,
                opp_action_count,
                ..SearchStats::default()
            };
            let mut root_analyses = Vec::with_capacity(my_actions.len());
            let mut root_values = vec![f32::NEG_INFINITY; my_actions.len()];
            let mut best_shallow_worst = f64::NEG_INFINITY;

            'outer: for (my_index, _) in my_order {
                if expired(deadline) {
                    break;
                }

                let my_action = my_actions[my_index].clone();
                let mut worst_score = f64::INFINITY;
                let mut mean_score = 0.0;
                let mut evaluated = 0_usize;
                let mut responses = Vec::with_capacity(opp_actions.len());

                for (opp_index, _) in opp_order.iter().copied() {
                    if expired(deadline) {
                        break 'outer;
                    }

                    let next = simulate_state(state, owner, &my_action, &opp_actions[opp_index]);
                    let score = evaluate(&next, owner, CONTEST_MAX_TURNS, &config.eval);
                    stats.root_pairs += 1;
                    worst_score = worst_score.min(score);
                    mean_score += score;
                    evaluated += 1;
                    responses.push(RootResponse { opp_index, score });

                    if allow_cutoff && worst_score < best_shallow_worst {
                        stats.cutoffs += 1;
                        break;
                    }
                }

                if evaluated == 0 {
                    continue;
                }

                mean_score /= evaluated as f64;

                let mut analysis = RootAnalysis {
                    action: my_action,
                    action_id: my_index,
                    worst_score,
                    mean_score,
                    responses,
                };
                refresh_root_analysis(&mut analysis, &mut root_values);
                best_shallow_worst = best_shallow_worst.max(analysis.worst_score);
                root_analyses.push(analysis);
            }

            if root_analyses.is_empty() {
                stats.elapsed_ms = started.elapsed().as_millis() as u64;
                return SearchOutcome {
                    action: PlayerAction::default(),
                    action_id: 0,
                    action_count: my_action_count.max(1),
                    root_values,
                    score: f64::NEG_INFINITY,
                    mean_score: f64::NEG_INFINITY,
                    stats,
                };
            }

            root_analyses.sort_by(|left, right| {
                right
                    .worst_score
                    .total_cmp(&left.worst_score)
                    .then_with(|| right.mean_score.total_cmp(&left.mean_score))
            });

            let deepen_top_my = config.search.deepen_top_my.min(root_analyses.len());
            for analysis in root_analyses.iter_mut().take(deepen_top_my) {
                if expired(deadline) || extra_nodes_remaining == 0 {
                    break;
                }
                stats.deepened_actions += 1;

                let mut response_indices = (0..analysis.responses.len()).collect::<Vec<_>>();
                response_indices.sort_by(|left, right| {
                    analysis.responses[*left]
                        .score
                        .total_cmp(&analysis.responses[*right].score)
                });

                for response_index in response_indices
                    .into_iter()
                    .take(config.search.deepen_top_opp.min(analysis.responses.len()))
                {
                    if expired(deadline) || extra_nodes_remaining == 0 {
                        break;
                    }
                    let next = simulate_state(
                        state,
                        owner,
                        &analysis.action,
                        &opp_actions[analysis.responses[response_index].opp_index],
                    );
                    let child_score = deepen_branch(
                        &next,
                        owner,
                        config,
                        deadline,
                        &mut extra_nodes_remaining,
                        &mut stats,
                    );
                    analysis.responses[response_index].score = child_score;
                }
                refresh_root_analysis(analysis, &mut root_values);
            }

            let best = root_analyses
                .iter()
                .max_by(|left, right| {
                    left.worst_score
                        .total_cmp(&right.worst_score)
                        .then_with(|| left.mean_score.total_cmp(&right.mean_score))
                })
                .expect("non-empty root analyses")
                .clone();

            stats.elapsed_ms = started.elapsed().as_millis() as u64;
            SearchOutcome {
                action: best.action,
                action_id: best.action_id,
                action_count: my_action_count.max(1),
                root_values,
                score: best.worst_score,
                mean_score: best.mean_score,
                stats,
            }
        }

        pub fn choose_action_unlimited(
            state: &GameState,
            owner: usize,
            config: &BotConfig,
        ) -> SearchOutcome {
            choose_action(
                state,
                owner,
                config,
                SearchBudget::ExtraNodesAfterRoot(u64::MAX / 4),
            )
        }

        fn deepen_branch(
            state: &GameState,
            owner: usize,
            config: &BotConfig,
            deadline: Option<Instant>,
            extra_nodes_remaining: &mut u64,
            stats: &mut SearchStats,
        ) -> f64 {
            let my_actions = ordered_joint_actions(state, owner);
            let opp_actions = ordered_joint_actions(state, 1 - owner);
            let default_action = PlayerAction::default();

            let mut my_order = (0..my_actions.len())
                .map(|idx| {
                    (
                        idx,
                        action_prior(state, owner, &my_actions[idx], &default_action, config),
                    )
                })
                .collect::<Vec<_>>();
            my_order.sort_by(|left, right| right.1.total_cmp(&left.1));

            let mut opp_order = (0..opp_actions.len())
                .map(|idx| {
                    (
                        idx,
                        action_prior(state, owner, &default_action, &opp_actions[idx], config),
                    )
                })
                .collect::<Vec<_>>();
            opp_order.sort_by(|left, right| left.1.total_cmp(&right.1));

            let mut best_followup = f64::NEG_INFINITY;
            for (my_index, _) in my_order
                .into_iter()
                .take(config.search.deepen_child_my.min(my_actions.len()))
            {
                if expired(deadline) || *extra_nodes_remaining == 0 {
                    break;
                }
                let mut child_worst = f64::INFINITY;
                for (opp_index, _) in opp_order
                    .iter()
                    .copied()
                    .take(config.search.deepen_child_opp.min(opp_actions.len()))
                {
                    if expired(deadline) || *extra_nodes_remaining == 0 {
                        break;
                    }
                    *extra_nodes_remaining -= 1;
                    stats.extra_nodes += 1;
                    let next = simulate_state(
                        state,
                        owner,
                        &my_actions[my_index],
                        &opp_actions[opp_index],
                    );
                    let score = evaluate(&next, owner, CONTEST_MAX_TURNS, &config.eval);
                    child_worst = child_worst.min(score);
                }
                if child_worst.is_finite() {
                    best_followup = best_followup.max(child_worst);
                }
            }

            if best_followup.is_finite() {
                best_followup
            } else {
                evaluate(state, owner, CONTEST_MAX_TURNS, &config.eval)
            }
        }

        fn refresh_root_analysis(analysis: &mut RootAnalysis, root_values: &mut [f32]) {
            if analysis.responses.is_empty() {
                analysis.worst_score = f64::NEG_INFINITY;
                analysis.mean_score = f64::NEG_INFINITY;
                root_values[analysis.action_id] = f32::NEG_INFINITY;
                return;
            }

            analysis.worst_score = analysis
                .responses
                .iter()
                .map(|response| response.score)
                .fold(f64::INFINITY, f64::min);
            analysis.mean_score = analysis
                .responses
                .iter()
                .map(|response| response.score)
                .sum::<f64>()
                / analysis.responses.len() as f64;
            root_values[analysis.action_id] = analysis.worst_score as f32;
        }

        fn action_prior(
            state: &GameState,
            owner: usize,
            my_action: &PlayerAction,
            opp_action: &PlayerAction,
            config: &BotConfig,
        ) -> f64 {
            let next = simulate_state(state, owner, my_action, opp_action);
            evaluate(&next, owner, CONTEST_MAX_TURNS, &config.eval)
        }

        fn simulate_state(
            state: &GameState,
            owner: usize,
            my_action: &PlayerAction,
            opp_action: &PlayerAction,
        ) -> GameState {
            let mut next = state.clone();
            if owner == 0 {
                next.step(my_action, opp_action);
            } else {
                next.step(opp_action, my_action);
            }
            next
        }

        fn deadline_for_budget(started: Instant, budget: SearchBudget) -> Option<Instant> {
            match budget {
                SearchBudget::TimeMs(ms) => Some(started + Duration::from_millis(ms)),
                SearchBudget::ExtraNodesAfterRoot(_) => None,
            }
        }

        fn expired(deadline: Option<Instant>) -> bool {
            deadline.is_some_and(|deadline| Instant::now() >= deadline)
        }

        fn ordered_joint_actions(state: &GameState, owner: usize) -> Vec<PlayerAction> {
            let birds = state
                .birds_for_player(owner)
                .filter(|bird| bird.alive)
                .map(|bird| bird.id)
                .collect::<Vec<_>>();
            let mut result = Vec::new();
            let mut current = PlayerAction::default();
            enumerate_actions(state, &birds, 0, &mut current, &mut result);
            if result.is_empty() {
                result.push(PlayerAction::default());
            }
            result
        }

        fn enumerate_actions(
            state: &GameState,
            birds: &[i32],
            idx: usize,
            current: &mut PlayerAction,
            output: &mut Vec<PlayerAction>,
        ) {
            if idx == birds.len() {
                output.push(current.clone());
                return;
            }

            let bird_id = birds[idx];
            for command in ordered_commands_for_bird(state, bird_id) {
                match command {
                    BirdCommand::Keep => {
                        current.per_bird.remove(&bird_id);
                    }
                    BirdCommand::Turn(direction) => {
                        current
                            .per_bird
                            .insert(bird_id, BirdCommand::Turn(direction));
                    }
                }
                enumerate_actions(state, birds, idx + 1, current, output);
            }
            current.per_bird.remove(&bird_id);
        }

        fn ordered_commands_for_bird(state: &GameState, bird_id: i32) -> Vec<BirdCommand> {
            let Some(bird) = state
                .birds
                .iter()
                .find(|bird| bird.id == bird_id && bird.alive)
            else {
                return Vec::new();
            };
            let facing = bird.facing();
            let mut commands = vec![BirdCommand::Keep];
            if facing == Direction::Unset {
                for direction in Direction::ALL {
                    commands.push(BirdCommand::Turn(direction));
                }
                return commands;
            }

            commands.push(BirdCommand::Turn(turn_left(facing)));
            commands.push(BirdCommand::Turn(turn_right(facing)));
            commands
        }

        fn turn_left(direction: Direction) -> Direction {
            match direction {
                Direction::North => Direction::West,
                Direction::West => Direction::South,
                Direction::South => Direction::East,
                Direction::East => Direction::North,
                Direction::Unset => Direction::Unset,
            }
        }

        fn turn_right(direction: Direction) -> Direction {
            match direction {
                Direction::North => Direction::East,
                Direction::East => Direction::South,
                Direction::South => Direction::West,
                Direction::West => Direction::North,
                Direction::Unset => Direction::Unset,
            }
        }

        pub fn render_action(action: &PlayerAction) -> String {
            let mut commands = action
                .per_bird
                .iter()
                .filter_map(|(bird_id, command)| match command {
                    BirdCommand::Keep => None,
                    BirdCommand::Turn(direction) => {
                        Some(format!("{} {}", bird_id, direction_to_word(*direction)))
                    }
                })
                .collect::<Vec<_>>();
            commands.sort();
            if commands.is_empty() {
                "WAIT".to_owned()
            } else {
                commands.join(";")
            }
        }

        fn direction_to_word(direction: Direction) -> &'static str {
            match direction {
                Direction::North => "UP",
                Direction::East => "RIGHT",
                Direction::South => "DOWN",
                Direction::West => "LEFT",
                Direction::Unset => "UP",
            }
        }
    }
}

use std::io::{self, BufRead, BufReader, Write};

use bot::config::BotConfig;
use bot::input::{BotIo, FrameObservation};
use bot::search::{choose_action, live_budget_for_turn, render_action};
use engine::{GameState, PlayerAction};

fn main() -> io::Result<()> {
    let stdin = io::stdin();
    let stdout = io::stdout();
    let mut reader = BufReader::new(stdin.lock());
    let mut writer = io::BufWriter::new(stdout.lock());
    let bot = Bot::new(BotIo::read(&mut reader)?);
    bot.run(&mut reader, &mut writer)
}

struct Bot {
    config: BotConfig,
    io: BotIo,
    state: Option<GameState>,
    last_my_action: PlayerAction,
}

impl Bot {
    fn new(io: BotIo) -> Self {
        Self {
            config: BotConfig::embedded(),
            io,
            state: None,
            last_my_action: PlayerAction::default(),
        }
    }

    fn run(mut self, reader: &mut impl BufRead, writer: &mut impl Write) -> io::Result<()> {
        let debug_stats = std::env::var_os("SNAKEBOT_DEBUG_STATS").is_some();
        while let Some(frame) = self.io.read_frame(reader)? {
            let state = self.reconcile_state(&frame);
            let budget = live_budget_for_turn(&self.config, state.turn);
            let outcome = choose_action(&state, self.io.player_index, &self.config, budget);
            if debug_stats {
                eprintln!(
                    "turn={} elapsed_ms={} root_pairs={} extra_nodes={} cutoffs={}",
                    state.turn,
                    outcome.stats.elapsed_ms,
                    outcome.stats.root_pairs,
                    outcome.stats.extra_nodes,
                    outcome.stats.cutoffs
                );
            }
            let command = render_action(&outcome.action);
            writeln!(writer, "{command}")?;
            writer.flush()?;
            self.last_my_action = outcome.action;
            self.state = Some(state);
        }
        Ok(())
    }

    fn reconcile_state(&self, frame: &FrameObservation) -> GameState {
        let observed_signature = self.io.observation_signature(frame);
        let fallback = if let Some(previous) = &self.state {
            self.io
                .build_visible_state(frame, previous.losses, previous.turn + 1)
        } else {
            self.io.build_visible_state(frame, [0, 0], 0)
        };

        let Some(previous) = &self.state else {
            return fallback;
        };

        let opponent = 1 - self.io.player_index;
        for opp_action in previous.legal_joint_actions(opponent) {
            let mut simulated = previous.clone();
            if self.io.player_index == 0 {
                simulated.step(&self.last_my_action, &opp_action);
            } else {
                simulated.step(&opp_action, &self.last_my_action);
            }
            if self.io.visible_signature(&simulated) == observed_signature {
                return simulated;
            }
        }

        if std::env::var_os("SNAKEBOT_STRICT_RECONCILE").is_some() {
            panic!("reconcile_state fell back to visible reconstruction");
        }

        fallback
    }
}
